services:
  fraud_node:
    build: .
    container_name: fraud_node
    ports:
      # HostPort:ContainerPort
      - "2021:21"
      - "21120-21130:21120-21130"
    volumes:
      # This maps the container's FTP folder to your local Linux machine
      # so you can easily see the files Java sends without entering the container!
      - ./local_received_cdrs:/home/fraud_user/ftp/received_cdrs
