services:
  billing-node:
    build: .
    container_name: billing-node

    ports:
      - "2223:22"

    volumes:
      - ./data:/home/billing

    restart: always

    networks:
      telecom-network:
        ipv4_address: 172.30.0.40

networks:
  telecom-network:
    external: true
