services:
  pgw_node:
    build: .
    container_name: pgw_node
    ports:
      - "2323:2323"
      - "21011-21021:21011-21021"
    
    networks:
      telecom-network:
        ipv4_address: 172.30.0.50

networks:
  telecom-network:
    external: true