services:
  smsc-node:
    build: .
    container_name: smsc-node

    ports:
      - "2222:22"

    volumes:
      - ./data/cdrs:/home/smsc/cdrs     
      - ./data/archive:/home/smsc/archive

    networks:
      telecom-network:
        ipv4_address: 172.30.0.30

networks:
  telecom-network:
    external: true
